# Controls when the action will run.
on:
  push:
    branches:
      - development
      - production
      - test
      - uat

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [Development, Test, UAT, Production]
        ref: ['development', 'test', 'uat', 'production']
        environment-lowercase: [development, test, uat, production]
    concurrency: ${{ matrix['environment-lowercase'] }}_environment
    steps:
      - name: Set environment name
        id: set-env
        run: echo "ref_name=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Deploy
        uses: ./.github/workflows/deploy-reusable.yml
        with:
          environment: ${{ matrix.environment }}
          ref: ${{ matrix.ref }}
        if: ${{ github.ref_name == matrix.ref }}
