name: Deploy Reusable

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: env
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy
        run: echo "Deploying to ${{ vars.v }}"
