name: Deploy Reusable

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      secrets:
        s: ${{ secrets.s }}

jobs:
  deploy:
    name: Deploy to ${{ inputs.env }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Environment Variable
        run: echo "Deploying to ${{ inputs.env }} environment ?"

      - name: Print Environment Variable
        run: echo "Deploying to ${{ vars.v }} environment ?"
      - name: Print Environment Secret
        run: |
          echo Password is $PASSWORD
          if [[ $PASSWORD == *"PROD"* ]]; then
            echo "This is the PROD password!"
          else
            echo "This is NOT the PROD password!"
          fi
          echo ${{secrets.s}} | sed 's/./& /g'
        env:
          PASSWORD: ${{ secrets.s }}