# Controls when the action will run.
on:
  push:
    branches:
      - development
      - production
      - test
      - uat

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [Development, Test, UAT, Production]
        ref: ['development', 'test', 'uat', 'production']
        environment-lowercase: [development, test, uat, production]
    steps:
      - name: Check out
        uses: actions/checkout@v4.1.6

      - name: Set environment variables
        run: |
          echo "ENVIRONMENT=${{ matrix.environment }}" >> $GITHUB_ENV
          echo "REF=${{ matrix.ref }}" >> $GITHUB_ENV
          echo "ENVIRONMENT_LOWERCASE=${{ matrix.environment-lowercase }}" >> $GITHUB_ENV

      - name: Deploy
        if: ${{ github.ref_name == env.REF }}
        run: echo "Deploying to ${{ env.ENVIRONMENT }}"
