# .github/workflows/deploy.yml

name: Deploy

on:
  push:
    branches:
      - development
      - production
      - test
      - uat

jobs:
  deploy-development:
    if: github.ref_name == 'development'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout

      - name: Trigger reusable workflow for Development
        uses: ./.github/workflows/deploy-reusable.yml
        with:
          environment: Development

  deploy-test:
    if: github.ref_name == 'test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout

      - name: Trigger reusable workflow for Test
        uses: ./.github/workflows/deploy-reusable.yml
        with:
          environment: Test

  deploy-uat:
    if: github.ref_name == 'uat'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout

      - name: Trigger reusable workflow for UAT
        uses: ./.github/workflows/deploy-reusable.yml
        with:
          environment: UAT

  deploy-production:
    if: github.ref_name == 'production'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout

      - name: Trigger reusable workflow for Production
        uses: ./.github/workflows/deploy-reusable.yml
        with:
          environment: Production
