name: Deploy Reusable

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Environment Variable
        run: echo "Deploying to ${{ inputs.env }} environment"

      - name: Print Variable from vars.v
        env:
          DEPLOY_ENV: ${{ vars.v }}
        run: echo "Value of vars.v: $DEPLOY_ENV"
